### ISSUE TITLE
Separate css from the html

### ISSUE THREAD

**Issue by DyonR** [DyonR/isheadyback.nl#2]
Make a separate layout.css file at the following location:
css/layout.css

Add this css/layout.css to the stylesheet of the html code instead.

**Comment by psyduck1203** [comment]
hey can i work on this issue ?

**Comment by DyonR** [comment]
Sure, go ahead!

Op do 6 aug. 2020 18:02 schreef Omkar <notifications@github.com>:

**Comment by DyonR** [comment]
This was fixed with Pull Request #4 already, closing this 😃
